# Generated by Django 6.1.1 on 2026-09-06 15:17

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import application1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "userRole",
                    models.CharField(
                        choices=[
                            ("GLOBAL_ADMIN", "Global Admin"),
                            ("ADMIN", "Admin"),
                            ("EMPLOYEE", "Employee"),
                            ("CLIENT", "Client"),
                        ],
                        default="EMPLOYEE",
                        max_length=20,
                        verbose_name="User Role",
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientBilling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoiceNumber",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                ("invoiceDate", models.DateField(verbose_name="Invoice Date")),
                ("dueDate", models.DateField(verbose_name="Due Date")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "taxAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "totalAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "paidAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "billingStatus",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Billing Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_billings_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_billings_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paymentDate", models.DateField(verbose_name="Payment Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Payment Amount"
                    ),
                ),
                (
                    "paymentMethod",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "transactionReference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Transaction Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="application1.clientbilling",
                        verbose_name="Billing",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_payments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Department "
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Designation "
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designation_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application1.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designation_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employeeName",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Employee Name "
                    ),
                ),
                (
                    "employeeID",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Eomplyee ID"
                    ),
                ),
                (
                    "employeeEmail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Eomplyee Email"
                    ),
                ),
                (
                    "employeePanNumber",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Employee PanCard Numebr",
                    ),
                ),
                (
                    "employeeStatus",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pendding", "Pending"),
                            ("Terminated", "Terminated"),
                        ],
                        default="Active",
                        max_length=100,
                        unique=True,
                        verbose_name="Employee Status ",
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeescreated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application1.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application1.designation",
                        verbose_name="Designation",
                    ),
                ),
                (
                    "reportingManager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportingEmployees",
                        to="application1.employees",
                        verbose_name="Reporting Manager",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeesupdated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=application1.models.employee_image_path,
                        verbose_name="Employee Image",
                    ),
                ),
                (
                    "imageName",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Image Name"
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeeImage_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeeImage_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="application1.employees",
                        verbose_name="Employees",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=application1.models.employee_file_path,
                        verbose_name="Employee Image",
                    ),
                ),
                (
                    "fielName",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Image Name"
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeeFile_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employeeFile_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="application1.employees",
                        verbose_name="Employees",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effectiveFrom", models.DateField(verbose_name="Effective From")),
                (
                    "effectiveTo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective To"
                    ),
                ),
                (
                    "basicSalary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Basic Salary",
                    ),
                ),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="HRA"
                    ),
                ),
                (
                    "conveyanceAllowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Conveyance Allowance",
                    ),
                ),
                (
                    "medicalAllowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Medical Allowance",
                    ),
                ),
                (
                    "otherAllowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Other Allowance",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Bonus"
                    ),
                ),
                (
                    "grossSalary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Gross Salary",
                    ),
                ),
                (
                    "pfDeduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="PF Deduction",
                    ),
                ),
                (
                    "professionalTax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Professional Tax",
                    ),
                ),
                (
                    "incomeTax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Income Tax",
                    ),
                ),
                (
                    "otherDeduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Other Deduction",
                    ),
                ),
                (
                    "totalDeduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Deduction",
                    ),
                ),
                (
                    "netSalary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Net Salary",
                    ),
                ),
                (
                    "salaryStatus",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Salary Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_salaries_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_details",
                        to="application1.employees",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_salaries_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "projectName",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Project Name"
                    ),
                ),
                (
                    "projectCode",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Project Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Project Description"),
                ),
                ("startDate", models.DateField(verbose_name="Start Date")),
                (
                    "endDate",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Project Status",
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directed_projects",
                        to="application1.employees",
                        verbose_name="Project Director",
                    ),
                ),
                (
                    "projectManager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to="application1.employees",
                        verbose_name="Project Manager",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clientbilling",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_billings",
                to="application1.project",
                verbose_name="Project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budgetName",
                    models.CharField(max_length=200, verbose_name="Budget Name"),
                ),
                (
                    "totalBudget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Budget",
                    ),
                ),
                (
                    "approvedBudget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Approved Budget",
                    ),
                ),
                (
                    "budgetStatus",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Budget Status",
                    ),
                ),
                ("startDate", models.DateField(verbose_name="Start Date")),
                (
                    "endDate",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_budgets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_budgets_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expenseTitle",
                    models.CharField(max_length=200, verbose_name="Expense Title"),
                ),
                (
                    "expenseCategory",
                    models.CharField(
                        choices=[
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("SOFTWARE", "Software"),
                            ("HARDWARE", "Hardware"),
                            ("TRAVEL", "Travel"),
                            ("TRAINING", "Training"),
                            ("LICENSE", "License"),
                            ("OFFICE", "Office"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Expense Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("expenseDate", models.DateField(verbose_name="Expense Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                (
                    "expenseStatus",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Expense Status",
                    ),
                ),
                (
                    "vendorName",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Vendor Name"
                    ),
                ),
                (
                    "invoiceNumber",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Invoice Number"
                    ),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "approvedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_project_expenses",
                        to="application1.employees",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="application1.projectbudget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_expenses_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sprintName",
                    models.CharField(max_length=100, verbose_name="Sprint Name"),
                ),
                (
                    "sprintCode",
                    models.CharField(max_length=50, verbose_name="Sprint Code"),
                ),
                (
                    "sprintGoal",
                    models.TextField(blank=True, verbose_name="Sprint Goal"),
                ),
                ("startDate", models.DateField(verbose_name="Start Date")),
                (
                    "storyPoints",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Story Points",
                    ),
                ),
                (
                    "capacityHours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Capacity Hours",
                    ),
                ),
                ("endDate", models.DateField(verbose_name="End Date")),
                (
                    "sprintStatus",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Sprint Status",
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprints_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprints_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ["startDate"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taskName",
                    models.CharField(max_length=200, verbose_name="Task Name"),
                ),
                (
                    "taskDescription",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                (
                    "taskStatus",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("TESTING", "Testing"),
                            ("ON_HOLD", "On Hold"),
                            ("CANCELLED", "Cancelled"),
                            ("RESOLVED", "Resolved"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="TODO",
                        max_length=20,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "sprintStartedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sprint Started Date"
                    ),
                ),
                (
                    "sprintEndDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sprint End Date"
                    ),
                ),
                (
                    "spintCount",
                    models.IntegerField(default=0, verbose_name="Spint Count"),
                ),
                ("startDate", models.DateField(verbose_name="Start Date")),
                (
                    "dueDate",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "completedDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "estimatedHours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Estimated Hours",
                    ),
                ),
                (
                    "actualHours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Actual Hours",
                    ),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "assignedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_project_tasks",
                        to="application1.employees",
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "closedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_closed",
                        to="application1.employees",
                        verbose_name="Closed By",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tasks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "developedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_developed",
                        to="application1.employees",
                        verbose_name="Developed By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_tasks",
                        to="application1.employees",
                        verbose_name="Assigned Employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "reviewedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_reviewed",
                        to="application1.employees",
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="application1.projectsprint",
                        verbose_name="Sprint",
                    ),
                ),
                (
                    "testedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_tested",
                        to="application1.employees",
                        verbose_name="Tested By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tasks_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectEmployeeCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("startDate", models.DateField(verbose_name="Start Date")),
                ("endDate", models.DateField(verbose_name="End Date")),
                (
                    "workingHours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Working Hours",
                    ),
                ),
                (
                    "hourlyRate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Hourly Rate",
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "costStatus",
                    models.CharField(
                        choices=[
                            ("ESTIMATED", "Estimated"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                        ],
                        default="ESTIMATED",
                        max_length=20,
                        verbose_name="Cost Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_costs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_employee_costs",
                        to="application1.employees",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_costs",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_costs_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_costs",
                        to="application1.projectsprint",
                        verbose_name="Sprint",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_costs",
                        to="application1.projecttask",
                        verbose_name="Task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientBillingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unitPrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Amount",
                    ),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_items",
                        to="application1.clientbilling",
                        verbose_name="Billing",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_items",
                        to="application1.projecttask",
                        verbose_name="Task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachmentType",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("FILE", "File"),
                            ("VIDEO", "Video"),
                            ("LINK", "Link"),
                        ],
                        max_length=20,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="project_tasks/files/",
                        verbose_name="File",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="External Link",
                    ),
                ),
                (
                    "attachmentName",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Attachment Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Attachment Description"),
                ),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="application1.projecttask",
                        verbose_name="Project Task",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rolename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("createdBy", models.CharField(verbose_name="Created By")),
                ("updatedBy", models.CharField(verbose_name="Created By")),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Updated Date"
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application1.designation",
                        verbose_name="Designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "joinedDate",
                    models.DateField(auto_now_add=True, verbose_name="Joined Date"),
                ),
                ("isActive", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_team_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assignments",
                        to="application1.employees",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="application1.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "reportingTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_members",
                        to="application1.projectteam",
                        verbose_name="Reporting To",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_team_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "projectRole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_team_members",
                        to="application1.roles",
                        verbose_name="Project Role",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employees",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="application1.roles",
                verbose_name="Roles",
            ),
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "oldStatus",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Old Status"
                    ),
                ),
                (
                    "newStatus",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="New Status"
                    ),
                ),
                ("action", models.CharField(max_length=200, verbose_name="Action")),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_history_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_history",
                        to="application1.employees",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="application1.projecttask",
                        verbose_name="Task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkItemType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Work Item Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("isActive", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "createdDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updatedDate",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_item_types_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_item_types_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projecttask",
            name="workItemType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_tasks",
                to="application1.workitemtype",
                verbose_name="Work Item Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsprint",
            constraint=models.UniqueConstraint(
                fields=("project", "sprintCode"), name="unique_project_sprint_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectteam",
            constraint=models.UniqueConstraint(
                fields=("project", "employee"), name="unique_employee_project"
            ),
        ),
    ]
