# Generated by Django 6.1.1 on 2026-09-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0002_rename_fielname_employeefile_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="spintCount",
        ),
        migrations.AddField(
            model_name="projecttask",
            name="sprintCount",
            field=models.IntegerField(default=0, verbose_name="Sprint Count"),
        ),
        migrations.AlterField(
            model_name="clientbillingitem",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_task",
                to="application1.projecttask",
                verbose_name="Task",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
        migrations.AlterField(
            model_name="designation",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
        migrations.AlterField(
            model_name="employeefile",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
        migrations.AlterField(
            model_name="employeeimage",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="createdBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="updatedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
        migrations.AlterField(
            model_name="projectexpense",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_budget",
                to="application1.projectbudget",
                verbose_name="Budget",
            ),
        ),
        migrations.AlterField(
            model_name="projectexpense",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_details",
                to="application1.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
        ),
    ]
