# Generated by Django 6.1.1 on 2026-09-18 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_remove_roles_designation_remove_user_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
        ),
    ]
