# Generated by Django 6.1.1 on 2026-09-21 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0008_otpvalues"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_code", models.CharField(max_length=50, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "website_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "domain_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("subdomain", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "company_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies/logos/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies/favicons/"
                    ),
                ),
                ("primary_color", models.CharField(default="#1976D2", max_length=20)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=20)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("subscription_plan", models.CharField(default="FREE", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "companies",
                "ordering": ["company_name"],
            },
        ),
        migrations.RemoveField(
            model_name="reportsdetails",
            name="analysis",
        ),
        migrations.AddField(
            model_name="clientbilling",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="clientbillingitem",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="clientpayment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="employeefile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="employeeimage",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="otpvalues",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projectbudget",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projectemployeecost",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projectexpense",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projectsprint",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projecttaskattachment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="projectteam",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="roles",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="workitemtype",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="application1.company",
                verbose_name="Company",
            ),
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "joinedDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined Date"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="application1.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_memberships",
                        to="application1.roles",
                        verbose_name="Role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Analysis",
        ),
        migrations.DeleteModel(
            name="ReportsDetails",
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_user_company_membership"
            ),
        ),
    ]
